<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3d_kitecom"
 *
 * Auto generated by Extension Builder 2013-10-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Kitecom',
	'description' => 'Kiteschools, Kitespots, Flats, Shops...',
	'category' => 'plugin',
	'author' => 'Ramon',
	'author_email' => 'rm@t3-design.ch',
	'author_company' => 'www.t3-design.ch',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'test',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>