<?php
return array(
	'BE' => array(
		'disable_exec_function' => 0,
		'installToolPassword' => '005f0ae495a0976993aa3603cb51de5e',
		'loginSecurityLevel' => 'normal',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'barbatt_kitecom2013',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'barbatt.mysql.db.internal',
		'password' => '$more5ekur4All',
		'username' => 'barbatt_t3d',
	),
	'EXT' => array(
		'extCache' => '0',
		'extConf' => array(
			'community' => 'a:0:{}',
			'datamints_feuser' => 'a:3:{s:10:"enableIrre";s:1:"0";s:13:"encryptionKey";s:32:"b98OQ8c5hhmH1dwVyk3po8K8I9kQ0KHm";s:16:"enableSalesforce";s:1:"0";}',
			'disqus_comments' => 'a:2:{s:15:"disqusshortname";s:7:"Kitecom";s:14:"disqusint3blog";s:1:"0";}',
			'div2007' => 'a:0:{}',
			'dix_easylogin' => 'a:1:{s:14:"addRealurlConf";s:1:"1";}',
			'extbase' => 'a:0:{}',
			'extbase_ajax' => 'a:0:{}',
			'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:1:"1";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
			'femanager' => 'a:2:{s:13:"disableModule";s:1:"0";s:10:"disableLog";s:1:"0";}',
			'feuser' => 'a:0:{}',
			'fluid' => 'a:0:{}',
			'image_crop' => 'a:1:{s:12:"enableDevLog";s:1:"0";}',
			'its_rsaajaxlogin_v2' => 'a:0:{}',
			'ni_feuserx' => 'a:0:{}',
			'ods_ajaxfelogin' => 'a:0:{}',
			'phpmyadmin' => 'a:5:{s:12:"hideOtherDBs";s:1:"1";s:9:"uploadDir";s:21:"uploads/tx_phpmyadmin";s:10:"allowedIps";s:0:"";s:12:"useDevIpMask";s:1:"0";s:10:"ajaxEnable";s:1:"1";}',
			'pt_extbase' => 'a:0:{}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'recycler' => 'a:0:{}',
			'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
			'saltedpasswords' => 'a:7:{s:20:"checkConfigurationFE";s:1:"0";s:20:"checkConfigurationBE";s:1:"0";s:3:"FE.";a:5:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:31:"tx_saltedpasswords_salts_phpass";s:11:"forceSalted";s:1:"0";s:15:"onlyAuthService";s:1:"0";s:12:"updatePasswd";s:1:"1";}s:3:"BE.";a:5:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:31:"tx_saltedpasswords_salts_phpass";s:11:"forceSalted";s:1:"0";s:15:"onlyAuthService";s:1:"0";s:12:"updatePasswd";s:1:"1";}s:21:"checkConfigurationFE2";s:1:"0";s:21:"checkConfigurationBE2";s:1:"0";s:8:"__meta__";N;}',
			'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
			'sr_feuser_register' => 'a:3:{s:12:"uploadFolder";s:27:"uploads/tx_srfeuserregister";s:10:"imageTypes";s:30:"png, jpg, jpeg, gif, tif, tiff";s:12:"imageMaxSize";s:3:"800";}',
			'static_info_tables' => 'a:3:{s:13:"enableManager";s:1:"0";s:5:"dummy";s:1:"0";s:7:"charset";s:5:"utf-8";}',
			't3d_kitecom' => 'a:0:{}',
			'tnm_redirect_felogin' => 'a:0:{}',
			'user_fjx050' => 'a:0:{}',
			'user_fjx164' => 'a:0:{}',
			'version' => 'a:0:{}',
			'workspaces' => 'a:0:{}',
			'xajax' => 'a:0:{}',
		),
		'extListArray' => array(
			'info',
			'perm',
			'func',
			'filelist',
			'about',
			'version',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'rtehtmlarea',
			'css_styled_content',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'form',
			'recycler',
			'scheduler',
			'workspaces',
			'extension_builder',
			'rsaauth',
			'saltedpasswords',
			'pt_extbase',
			'extbase_ajax',
			'its_rsaajaxlogin_v2',
			'static_info_tables',
			'div2007',
			'phpmyadmin',
			'sr_feuser_register',
			'femanager',
			'datamints_feuser',
			't3d_kitecom',
			'image_crop',
			'realurl',
			'dix_easylogin',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'de',
			),
		),
	),
	'FE' => array(
		'loginSecurityLevel' => 'normal',
	),
	'GFX' => array(
		'colorspace' => 'sRGB',
		'gdlib_png' => 1,
		'im' => 1,
		'im_combine_filename' => 'composite',
		'im_path' => '/usr/local/bin/',
		'im_path_lzw' => '/usr/local/bin/',
		'jpg_quality' => '100',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
		),
	),
	'SYS' => array(
		'compat_version' => '6.1',
		'curlUse' => '1',
		'doNotCheckReferer' => '1',
		'encryptionKey' => '3f57c626cafbff41661cf3c8ba01a2eb7692a6324119e0af9bf97227686ed8a3134c3969e0124502fedf3f5017cbb494',
		'setMemoryLimit' => '250',
		'sitename' => 'Kitecom.net',
	),
);
?>